---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: 5-demo-helm-release-git-helm-bb-app
  namespace: flux-system
spec:
  chart:
    spec:
      chart: helm-chart
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: 5-demo-source-git-bb-app
  interval: 10s
  targetNamespace: 5-demo
  values:
    image:
      pullPolicy: Always
      repository: siddharth67/block-buster-dev:7.5.0
      tag: ""
    labels:
      env: dev
      name: bb-app
      version: 7.5.0
    namespace:
      name: 5-demo
    replicaCount: 2
    service:
      nodePort: 30005
      type: NodePort
